### ISSUE TITLE
frontend & backend structure (React/PHP)

### ISSUE THREAD

**Issue by Ronin-0822** [aaron-san/vocab-builder#1]
I've been looking into how to structure a React app with a PHP backend, and came across [this post](https://www.dhiwise.com/post/the-synergy-between-php-and-react-in-modern-web-applications).

I haven't read it completely yet, but it looks like it might be helpful. I agree with it saying that having a clear folder structure is essential. Typically, the React application has its own directory within the project, often labeled client or frontend, while the PHP codebase is located in a server or backend directory. This separation makes things a lot easier to work with and maintain.

Here's the post's example for folder structure:

    /my-app   
        /client
            /src
            /public
        /server
           /config
           /public
           /src

If it's ok, I'll go ahead and open a new branch and implement the MVC framework in its own directory. Any preferences for naming? (backend or server?)

**Comment by aaron-san** [comment]
Yeah, I think that is a common approach. I was thinking about that as well, but I also thought it would be fine to keep the project's separate. I often forget what directory I'm in when I'm running commands on the terminal and accidentally install packages in the project root or server rather than on the client side. I end up having to use "cd" on the command line too often (of course after deleting the modules I accidentally installed). 

But, if you want to try that approach, it's fine with me! I'll have to learn from my mistakes sometime! 

Backend or server, either is okay!

**Comment by Ronin-0822** [comment]
Oh, ok. Do you mean treating them as 2 completely separate projects for learning purpose? Or merge them together at a later stage in development, after both frontend and backend have progressed a bit more?

Either way is fine with me.

**Comment by aaron-san** [comment]
Let's try to keep them separate for now. We may merge them later if necessary or convenient.

**Comment by Ronin-0822** [comment]
Sounds good to me.
